services:
  - type: web
    name: cs492-pizza-ordering-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --threads 4 --timeout 60 run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
